name: Build LaTeX PDF

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Add changelist number
        run: |
          echo "Adding changelist version..."
          CHANGE_NUM=$(git rev-list --count HEAD)
          sed -i "s/\\\def\\\version{.*/\\\def\\\version{${CHANGE_NUM}}/" main.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-output
          path: main.pdf
